### PR TITLE
Line revision 9900 to 10000+, 12350-12450, some other lines, Replaced Faint with Stunned, Magic field with Magic circle, other minor consistency changes

### PR DESCRIPTION
**Pull request by ttgmichael**
Title says it all. 

Revised/reviewed lines 9900 to 10000 plus lines here and there for consistency I noticed both stunned and faint being used, changed to stunned (best word for "to make faint" that I can think of in English). Both Magic field and Magic circle were used, Googling the korean term seems to lead more results towards Magic circle, so I'm putting it as magic circle.

Oh and I changed Chamber of Secrets to a different name (ToS isn't Harry Potter xD)

### CODE REVIEW

**Comment by vegax87** [comment]
Fainted is a term to describe a KO, a collapsed person or animal, and not a stun, when your mount dies you cannot ride it, of couse...

**Comment by ttgmichael** [comment]
I'll happily change it all to faint then? I am hesitant on thinking faint == KO like in Pokemon because of some lines:

ETC_20150317_002282 had its translation as:
You've been stunned by the root's poison and fainted!

Would the poison KO you? It felt more appropriate for stun.

ETC_20150323_009981 had its translation as:
Stun Scorpio to faint and extract poison

As least from the gameplay videos I watched, monsters that are killed will explode and disappear. So it wouldn't be possible to extract poison from the Scorpio if you are to KO it. Stun felt more appropriate (to immobilize the Scorpio/ make it unconscious).

ETC_20150714_012377 had its translation as:
You've shot Wendigo with the paralyzing needle!{nl}Pull out the hairs of fainted Wendigo Archer in 10 secs!

Why would a paralyzing needle faint/KO someone? It sounded more appropriate to use stun.

What are other peoples thoughts? ^^ @imcgames would help if you can clarify "faint"/stun (Korean term is 기절시키고 ), that'll help! :)

**Comment by ttgmichael** [comment]
Revised/reviewed lines 12352 to 12450 as well; Stun changed to Faint

**Comment by imcgames** [comment]
Well.. ETC_20150317_002282, ETC_20150714_012377 is more like it's fainted already
while ETC_20150323_009981 is to make faint.
So I guess use of faint/stun would depend on the lines?

**Comment by ttgmichael** [comment]
I've changed the wording so they can all be fainted :)

**Comment by imcgames** [comment]
Thank you :+1:

**Pull request merged**
