### PR TITLE
Update SKILL.tsv

### PR DESCRIPTION
**Pull request by Sunaries**
Minor fix to SKILL.
- Changed a few skill descriptions.

@imcgames: http://imgur.com/a/Ehc0o - Here is an album containing a few screenshots of skills where you can see cut-off variables in the tooltip.

GitHub Logo 

You can also see that long attribute names like the one above will overlap the UI. I can't make the name shorter since this is already at its best. Though, for this particular attribute name, I could remove 'basic attack' since it already tells you the effects in the description below. 

**A question**: Is there a way for me to try out different fonts in the game? I know that the game uses 2 fonts at this moment. imcm_book & imcm_original. 

I just would like to see what the game looks like with the following fonts:
- Raavi
- PF Din Text Cond Pro
- JejuGothic
- Noto Sans

Or maybe you can give me a preview with those fonts, please. :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by Soukyuu** [comment]
Ideally, when a string is too long, it should autowrap, not just run out of the tooltip. I think there are already tags that control alignment (left, center, right), so in this case it would autowrap nicely and increase the height of the tooltip by a bit.

**Comment by imcgames** [comment]
Replace  imcm_book & imcm_original with the fonts you'd like to use :wink:
( you need to rename the font file to imcm_book & imcm_original )

**Comment by Sunaries** [comment]
@imcgames Thank you. It worked. Is the font used in the 1st iCBT final? Or can we still send in suggestions with screenshots of course? 

Good to merge by the way.

**Comment by imcgames** [comment]
@Sunaries  I meant the one in release/languageData/English/font :smile:

**Comment by imcgames** [comment]
Thank you :smile:

**Pull request merged**
