### PR TITLE
Update ITEM.tsv

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by wlghksdl2** [comment]
Did you use machine translations?

**Comment by Chaosbelow** [comment]
These look machine translated. Please avoid machine translating lines especially when they are this jumbled and badly translated.

**Comment by vtange** [comment]
Lol Nuclear Weapons in ToS? I guess Terran Ghosts have invaded. Fix them or we have to close this.

**Comment by imcgames** [comment]
Seems machine translated as the comments say so we'll close this request :wink:

**Pull request closed without merging**
