### PR TITLE
Update QUEST_JOBSTEP.tsv [Lines 003 - 140]

### PR DESCRIPTION
**Pull request by terrapin47**
Grammar corrections, description corrections.

### CODE REVIEW

**Comment by Sunaries** [comment]
I see a few lines containing **Merogg**. This should be **Merog** for consistency.

**Comment by terrapin47** [comment]
Ah, thanks.  I'll make the changes now.

**Comment by cordogames** [comment]
Should also check to make sure you're not re-doing what people have already done:
https://github.com/Treeofsavior/EnglishTranslation/pull/764
https://github.com/Treeofsavior/EnglishTranslation/pull/767
https://github.com/Treeofsavior/EnglishTranslation/pull/768

**Comment by terrapin47** [comment]
Yes, although I believe I have made a couple of extra corrections.  I could incorporate these into your fork, or wait for your pull request to be resolved and resolve the merge conflicts myself at that time.

**Pull request closed without merging**
