### PR TITLE
Update UI.tsv

### PR DESCRIPTION
**Pull request by lifeiscontent**

### CODE REVIEW

**Comment by lifeiscontent** [comment]
I plan on creating several fixes, I'm a native english speaker but I don't currently own a beta key which would be nice.

I'm a big fan of the original Ragnarok, I even ran my own custom server software I built with a friend growing up. It's nice to see someone building a new game similar to what I loved playing growing up.

I Would love to get access and contribute to the game via translations. Possibly coding too if that's of any interest. I've got 16 years of programming experience

**Comment by vtange** [comment]
Old version is better. You actually right click other players' characters to do party requests.

You are welcome to help, but please don't come in to work just for the sake of getting a beta key. Many have done so in the past and it doesn't really help this project.

I don't think IMC's devs read the Github so it might be a stretch for them to add you in the dev team.

**Comment by Sunaries** [comment]
I suggest changing it to:

{@st59b}Party Information{nl}{@st59s} - Click on the Create Party button at the bottom to create a party. {nl} - Right-click on other players to send a party invite. {nl} - Changes can be made to the party in the Settings tab. {nl} - Set up specific search conditions for party members from the Public Party list.{/}

**Comment by lifeiscontent** [comment]
@vtange I'm not just trying to get a beta key here, I'd genuinely like to create meaningful fixes to the translations, though it is somewhat hard to do that being outside of the game.

**Comment by lifeiscontent** [comment]
Also, one thing that is a major improvement here is now we can actually see the entire rendered list of translations https://github.com/lifeiscontent/EnglishTranslation/blob/patch-1/UI.tsv

previously it wouldn't render due to using quotes.

**Comment by vtange** [comment]
:+1: Good to Merge

**Comment by imcgames** [comment]
:+1:

**Comment by lifeiscontent** [comment]
@imcgames now that this has been merged, can I get a beta key so I can make better contributions in the future?

**Comment by imcgames** [comment]
@lifeiscontent  Please check your email. you can see the beta key. Thank you.

**Pull request merged**
