### PR TITLE
Minor Update

### PR DESCRIPTION
**Pull request by Sunaries**
- Fixed inconsistencies.

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
@imcgames Good to merge.

**Comment by Sunaries** [comment]
DO NOT MERGE YET

**Comment by Sunaries** [comment]
@imcgames Good to merge. 
I've sent a question about the Contributor Benefit rewards on Discord and later through the Support ticket, hoping to get your attention.

By the way, in your newest update it says: ` - 특성 즉시 수련 가능{nl} - 마켓 판매 수수료율 감소(30%{img white_right_arrow 16 16}10%){nl} - 마켓 판매 등록 아이템 개수 5개{nl} - 캐릭터 이동속도 +3{nl} - 최대 버프 적용 개수 증가{nl} - 프리미엄 제스쳐 사용 가능{nl}` 

"마켓 판매 등록 아이템 개수 5개" 5? I thought the patch note for today's maintenance said 'increased to 10'.

**Comment by Sunaries** [comment]
@imcgames Good to merge. 
I've sent a question about the **Contributor Benefit rewards** on Discord and later through the Support ticket, hoping to get your attention.

I checked your latest Update - Steam Test Server, but I see this:: `- 특성 즉시 수련 가능{nl} - 마켓 판매 수수료율 감소(30%{img white_right_arrow 16 16}10%){nl} - 마켓 판매 등록 아이템 개수 5개{nl} - 캐릭터 이동속도 +3{nl} - 최대 버프 적용 개수 증가{nl} - 프리미엄 제스쳐 사용 가능{nl}` 

"마켓 판매 등록 아이템 개수 5개" 
5? But the [patch note for today's maintenance](https://forum.treeofsavior.com/t/update-server-transfer-maintenance-and-patch-notes-april-26th-2016/215880) says: **_"The number of items you can register on the market increases from 5 to 10"_**

**Comment by imcgames** [comment]
:+1:

**Comment by imcgames** [comment]
Just textual errors, from 5 to 10 is correct ^^

**Pull request merged**
