### PR TITLE
Update ETC_en.tsv

### PR DESCRIPTION
**Pull request by Sunaries**
Updated and fixed minor lines.

### CODE REVIEW

**Comment by vegax87** [comment]
ETC_20150317_008699 is Navigation Camera ON (F11)

with F12 you can save a recorded video.

**Comment by Sunaries** [comment]
@vegax87 The line clearly says camera and not recording a video. I believe this is a dev command.

**Comment by xapher19** [comment]
Just missed a space on ETC_20150317_008845 otherwise looks great :grinning:

**Comment by Sunaries** [comment]
@xapher19 Thanks!

**Comment by imcgames** [comment]
:+1:

**Pull request merged**
