### PR TITLE
Proofreading till completion of Great Cathedral, and a portion of Greene Manor

### PR DESCRIPTION
**Pull request by Sunaries**
Proofread the quests up to the end of the Great Cathedral and a portion of the Greene Manor.

@imcgames 
I want to tell you about something I experience:

Using Swordsman, whenever I sprint with mini map open, it always freezes me for a few seconds. This happens 100% every time. Bug? You can reproduce it yourself to check it.

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by terrapin47** [comment]
:+1:

**Comment by Sunaries** [comment]
Good to merge.

**Comment by imcgames** [comment]
Thank you the bug report. I will check it on our side.

**Pull request merged**
