### PR TITLE
Update ETC.tsv

### PR DESCRIPTION
**Pull request by Sunaries**
Despite the lag, some minor updates.

### CODE REVIEW

**Comment by emailboxu** [comment]
I think the blank lines are an issue on imc's part, Item.tsv is riddled with them as well. I am fairly certain they were not intended.

**Comment by Sunaries** [comment]
@emailboxu There are a lot of blank lines. It just means it is untranslated. I don't know who did the "N/A" part.

**Comment by imcgames** [comment]
Thank you :smile: 

(the N/A's were done by us intentionally for parts that shouldn't be translated.)

**Comment by Sunaries** [comment]
@imcgames Oh, I see. I didn't know that. Next time I see N/A, I'll skip it.

**Pull request merged**
