### PR TITLE
Steam Test Server - Update 11

### PR DESCRIPTION
**Pull request by Sunaries**
Proofread https://github.com/Treeofsavior/EnglishTranslation/commit/288762cad66c2c933608efbcbb575a137a2815be + https://github.com/Treeofsavior/EnglishTranslation/commit/92f2c65e35dbaa740261f5e8f0cbd74c0433e5e0

@imcgames Do you know when the _kor files will be updated to reflect the changes with the Korean version. Because I know a few skill descriptions have been changed and the Guild UI is a bit different. Thank you. :smile:

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by imcgames** [comment]
@Sunaries Current version or build on our Steam Test Server is actually final version for coming Steam OBT. ( But we will update some patch to fix bugs. )

I think the latest Korea files will be updated after Steam OBT. :+1:

**Pull request merged**
