### PR TITLE
Update SKILL.tsv Line 1004-1006, 4341, 4342: Skill Name Flange >> Frenzy

### PR DESCRIPTION
**Pull request by HilandLogic**
Changed Line 1004:
Skill Name Flange to Frenzy to better match Skill description and Attribute

Old Line 1004:
SKILL_20150317_001004   Flange

New Line 1004:
SKILL_20150317_001004   Frenzy

### CODE REVIEW

**Comment by Sunaries** [comment]
If you're contributing anyway, can you edit the following of Frenzy's description:

SKILL_20150317_001005 _to_: Increases your attack when you use consecutive basic attacks on the target.
SKILL_20150317_001006 _to_: Attack  +#{CaptionRatio}# {nl} Stacks up to #{CaptionRatio2}# times  {nl} Duration #{CaptionTime}# seconds

**Comment by HilandLogic** [comment]
Thanks and I would like to paraphrase your description if you don't mind.

Consecutive basic attacks on the target increases your attack

**Comment by Sunaries** [comment]
> Thanks and I would like to paraphrase your description if you don't mind.
> Consecutive basic attacks on the target increases your attack

It is better to write what the skill does in the beginning. It **increases your attack** _when_ ...

**Comment by HilandLogic** [comment]
Ahh I see.. Thanks for the info. I'll post the changes in a minute here.

**Comment by HilandLogic** [comment]
I put in your suggested changes and also updated the Attribute on line 4341 and 4342

Old
4341: SKILL_20150714_004341 Frenzy: Maintain the overlap
4342: SKILL_20150714_004342 Overlap of [Frenzy] will maintain while attacking the other enemy, but Max overlap will be reduced by half.

New
4341: SKILL_20150714_004341 Frenzy: Maintain Stacks
4342: SKILL_20150714_004342 Stacks of [Frenzy] will maintain while switching targets, but will be reduced by half.

**Comment by imcgames** [comment]
The Pull Request is closed for issues regarding copyrights as stated in our main page. 
We will be updating you with details in the near future regarding this matter so please hold your Pull Requests until things the issue is resolved. 
We apologize for the inconvenience caused.

**Pull request closed without merging**
