### PR TITLE
Update to SKILL.tsv [Lines 1 - 5039]

### PR DESCRIPTION
**Pull request by 511141**
Large update to skill.tsv

Notable changes:

Hit/blunt/strike changed to impact.
Skill names changed.

Lines 1-1800 have been proofread and translated/finalized. The remaining 3239 have had minor changes in regards to skill names and find and replace function working through them for general changes. Other then that they remain unchecked.

From the translation document:
https://docs.google.com/spreadsheets/d/1IUDSTR31ve9lQDn373Z5j0uNPNbCno3v9ypu8mE8sj4/edit?pli=1#gid=1552786996

Additional information:
Contains SKILL.tsv edits from https://github.com/Treeofsavior/EnglishTranslation/pull/896

### CODE REVIEW

**Comment by Sunaries** [comment]
**This pull request is too big**. We cannot see the changes that you have made. I consider this file important, because it caused a lot of confusion to the iCBT players. Therefore I'd like to see the changes that you have made. 
Also, I would like to prevent that this pull request might override your changes with mine https://github.com/Treeofsavior/EnglishTranslation/pull/881 (_already accepted_) since yours is different if you compare it.

That is why I prefer Github over Google Docs, because it allows me to see the history of any edit that has been made.

**Comment by 511141** [comment]
You can see all changes if you simply navigate to the translation document provided.
There is a hidden sheet named "original skill" which once inside, will show all original translations before being edited.

I am aware of the pull request #881 submitted. This document includes all #881 edits, and further "re-edits" of the now closed 'older' pull request mentioned in #881 's description.

Skill 001915 has now been edited as it was the only conflicting line from #881

**Comment by ttgmichael** [comment]
I took the time and went over the changes that this Skill file on Notepad++ has compared to the one in the rep right now;

The biggest change is Strike/Hit -> to Impact. IMC haven't actually finalized their call on whether we will be changing Hit/Strike to Impact, there seem to be 2 seperate terms for Hit and Strike. Refer to this discussion https://github.com/Treeofsavior/EnglishTranslation/issues/900

Another big change (or minor depending on how you see it) is just added commas to seperate skill descriptors (e.g. SKILL_20150317_000224    [Panto Shaman] Magic, Lightning Property"," Impact)
These commas that were added aren't in the Korean texts themselves, so I guess it's up to IMC to determine whether commas are just to seperate the descriptors from each other (if that's the case, the Korean text needs more commas)

SKILL_20150317_000191,192 Vubbe Thief is spelled incorrectly (Theif -> Thief)
SKILL_20150323_003120 finish is spelled wrong
SKILL_20150317_002822 has the _ in the Korean Text
SKILL_20150317_002824 has a 2 in the Korean Text
SKILL_20150317_002880 has the _ in the Korean Text
SKILL_20150317_002882 has a 2 in the Korean Text
SKILL_20150317_002942 has the _ in the Korean Text
SKILL_20150317_002958 has the _ in the Korean Text
SKILL_20150317_002960 has a 2 in the Korean Text
The old version of SKILL_20150317_001095 seem more accurate.
SKILL_20150317_001120 could be:
Creates a strong wind to knockback enemies. Inflicts damage to a target who is frozen or nearby an Ice Wall.
The old version of SKILL_20150317_001145 was more detailed/specific
(Release all connected links. -> Cut all links.)

SKILL_20150317_001023 and SKILL_20150317_001044 is wrong; please follow the Korean text, the old descriptions were correct translations. 
The old version of SKILL_20150317_001042 is more consistent with other skill descriptions

SKILL_20150317_001019 and SKILL_20150317_001021; repair weapon and repair armor were more accurate. The skill's purpose isn't solely to improve weapons and armor. (it's a bonus)

The PR does not contain all #881 edits (which WILL BE OVERWRITTEN D:): Namely all edits past SKILL_20150317_001900.

Skill names were changed to match the list I provide in this wiki https://github.com/ttgmichael/EnglishTranslation/wiki/2.C.%20Skills

In order for others to actually see the changes line by line conveniently (as no one other than you work on these lines), we'd like for the PR to be split up into 300-500 bits to see the changes more clearly.

**Comment by imcgames** [comment]
Thank you :+1: 

We'll skip the 'Impact' and comma additions for now :wink:

**Pull request merged**
