### PR TITLE
Update ETC.tsv (added latest KOR lines)

### PR DESCRIPTION
**Pull request by Sunaries**
Added the latest lines from the _kor file. The actual _kor file and the rest has to be updated by IMC.

@imcgames 

I noticed a new line that says: {Level} 레벨 - Where does this line apply to? It didn't seem to work on the skill and item descriptions. It would be great to have it for the skill and item descriptions, so that we can change it to "Level {Level}".

### CODE REVIEW

**Comment by terrapin47** [comment]
:+1:

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by imcgames** [comment]
Thank you :smile:  

(the latest lines added in Nexon client aren't necessarily the final version of lines that is used by English version so we removed the added lines :wink: )

**Pull request merged**
