### PR TITLE
Attempt to translate lines 12800 to 13000, fix typo on korean script

### PR DESCRIPTION
**Pull request by ttgmichael**
Attempt to translate lines 12800 to 13000, fix typo on korean script

### CODE REVIEW

**Comment by imcgames** [comment]
We'll go with stone frost since it's shorter :smile:

**Comment by imcgames** [comment]
Thank you :smile: 

(but you don't really need to translate lines with N/A in the future)

**Comment by ttgmichael** [comment]
oh, mmk! I thought someone just placed the n/a there because they couldn't find anything.

**Comment by ttgmichael** [comment]
@aFoSho haha, I didn't catch that (was reading from 12800 downwards). Will get that changed thanks! ;)

**Pull request merged**
