### PR TITLE
20140707_005530 - 20140707_005532; 20150317_003413 & 003472

### PR DESCRIPTION
**Pull request by WorksWellWithOthers**
Line 3413 
Line 3472
Line 5530 - Line 5532

### CODE REVIEW

**Comment by terrapin47** [comment]
Welcome!  Please check the issue https://github.com/Treeofsavior/EnglishTranslation/issues/850, and join us on discord ( instructions in the issue ).

**Comment by Ragunaga** [comment]
It's better to just say what line number, instead of the string of numbers for each element.
Just an FYI for future reference to make it easier on you and everyone else, and also we shouldn't send any more pull requests in till the 23rd.

**Comment by WorksWellWithOthers** [comment]
Thank you.

**Comment by Ragunaga** [comment]
Oh, I also just noticed it now. You did the 'x's wrong. They should be before the file's name on each line.

eg. "xITEM#######_###### (stuff)"

If the x is before the file's name the devs can easilly remove them before compiling them back in the game. Since every x will have a uniform entity infront of it they can just find all "x(Prefix)" and replace with just "(Prefix)."

**Comment by WorksWellWithOthers** [comment]
!!

**Comment by imcgames** [comment]
The Pull Request is closed for issues regarding copyrights as stated in our main page. 
We will be updating you with details in the near future regarding this matter so please hold your Pull Requests until things the issue is resolved. 
We apologize for the inconvenience caused.

**Pull request closed without merging**
