### PR TITLE
Update pet_dog NPC

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Sunaries** [comment]
Elaborate?

**Comment by ghost** [comment]
This line

> ETC_20150317_000580   개

Should correspond to the `pet_dog` pet npc (id 60002) and some other dog monster (id 41431).
Those might not be used in-game yet.

**Comment by Sunaries** [comment]
Ah, okay. It is a word with many meanings, but now I know the context. Thanks. 

Good to merge.

**Comment by imcgames** [comment]
:+1:

**Pull request merged**
