### PR TITLE
Minor update

### PR DESCRIPTION
**Pull request by Sunaries**
Minor update
- Added contributions by @shirousagi905254.
- Minor fixes.

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by imcgames** [comment]
Thanks @shirousagi905254 and @Sunaries :+1:

**Pull request merged**
