### PR TITLE
Update QUEST_JOBSTEP.tsv

### PR DESCRIPTION
**Pull request by Leeoku**
translated line 758-815

### CODE REVIEW

**Comment by Ihysoal** [comment]
This is machine translated?

**Comment by Ragunaga** [comment]
I definitly do not think those lines should have 'x's. They are not ready for the final game at all.
And as g1real said, is this machine translated?

**Comment by Leeoku** [comment]
Yea I followed this guide https://github.com/Treeofsavior/EnglishTranslation/wiki/1.%20How%20to%20Contribute
https://github.com/Treeofsavior/EnglishTranslation/wiki/Guidelines

**Comment by Ragunaga** [comment]
You're supposed to edit the translations and make it grammatically and contextually good tho. Not just copy/paste the whole thing and be done with it >m<

**Comment by Leeoku** [comment]
I really really tried, but a lot of those dont make sense... I'm just gonna do the simpler ones like items then -_-

**Comment by Ihysoal** [comment]
The problem with machine translations is that context or details might be lost and then people in the future will see and think "this is already translated, might as well skip it".

The desire to want to contribute is understood, but for people like you (and me) who do not understand korean it might be best to just leave it to the big guys.

Those guidelines are outdated by the way, imcgames themselves acknowledged that allowing machine translation to ease the process backfired on them.

**Comment by ttgmichael** [comment]
Haha, the Korean -> Japanese -> English way only works if you know Japanese very well and have brushed up on some basic Korean grammars/particles and stuff because of the similarities ^^. And it still is terrible when trying it with any lines with names in them. It'll be great for IMC to add that.

**Comment by imcgames** [comment]
The Pull Request is closed for issues regarding copyrights as stated in our main page. 
We will be updating you with details in the near future regarding this matter so please hold your Pull Requests until things the issue is resolved. 
We apologize for the inconvenience caused.

**Pull request closed without merging**
