### PR TITLE
Proofreading & fixes till Forest of Prayer

### PR DESCRIPTION
**Pull request by Sunaries**
- Changed a few instances where it said 'great wizard/magician' to Archmage. Agailla is an archmage.
- Changed 'Grand Mage' to 'Archmage' (e.g. Archmage Tower Dungeon)
- Changed a few instances where it said 'Cathedral' to 'Great Cathedral'
- Renamed 'Penitence Route of Cathedral' to 'Penitence Route of Great Cathedral' and mass replaced the former name.
- Renamed 'Plateau of Rex' to 'King's Plateau' based on IMC's response. 
  (https://github.com/Treeofsavior/EnglishTranslation/pull/1202#issuecomment-147309496)
- Renamed instances of Nuahella/Nuaelle to Nuaele based on IMC's response. (https://github.com/Treeofsavior/EnglishTranslation/pull/1202#issuecomment-147309496)
- Renamed 'Dionys' to 'Dionysus' 

Last time I asked you for a name check on 디오니스. Which is 'Dionys', but I have come across a sentence which mentions '주신' which is the god of wine. 
https://en.wikipedia.org/wiki/Dionysus <--- That is the official spelling, do you agree with this change to **Dionysus**?
- Added an extra space to the 'Repeatable' tag strings. Necessary.
- Fixed erroneous dialogue and standardization till Forest of Prayer.
- Proofread IMC's latest translated lines - Version 1.

@imcgames Can you help me with the name of '베이키얼' - I cannot really translate it to English and I've asked for help, but it's difficult. Vaykiel, Baykiel, Veykiel? Is it Lithuanian-based?

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge. @imcgames

**Comment by ttgmichael** [comment]
do this one first imc xD

**Comment by Sunaries** [comment]
Good to merge. @imcgames

**Comment by imcgames** [comment]
How about "Beikeol" it was named by our scenario writer. Yep, it is based on Lithuanian.

**Comment by Sunaries** [comment]
> How about "Beikeol" it was named by our scenario writer. Yep, it is based on Lithuanian.

Thanks. I will change it in my next pull request. :wink: If I come up with a more appropriate name, I will let you know of course.

**Comment by imcgames** [comment]
Thank you :+1:

**Pull request merged**
