### PR TITLE
Greene Manor, Shaton Farm, Shaton Reservoir (Complete)

### PR DESCRIPTION
**Pull request by Sunaries**
- Proofread quests and gameplay through Greene Manor, Shaton Farm and the Shaton Reservoir.
- Standardized and gave a few NPCs the correct name from IMC's newly translated lines.

@imcgames 

GitHub Logo

So, now all statuses affect Critical Attack & Critical Rate. My Critical Rate goes from 29 -> 13 and it's marked in green. Is this a bug?

### CODE REVIEW

**Comment by Sunaries** [comment]
@imcgames Good to merge.

**Comment by Sunaries** [comment]
@imcgames Good to merge.

**Comment by Sunaries** [comment]
@imcgames Good to merge.

**Comment by Sunaries** [comment]
@imcgames Good to merge.

**Comment by imcgames** [comment]
@Sunaries  Yes, it seems a bug. I will check it.

**Comment by Sunaries** [comment]
> @Sunaries Yes, it seems a bug. I will check it.

@imcgames Thanks. :) Good to merge by the way.

By the way, this is important!! https://github.com/Treeofsavior/EnglishTranslation/issues/1243 <--- Please respond, it is regarding translation of a certain word!!

**Comment by imcgames** [comment]
:+1:

**Pull request merged**
