### PR TITLE
Update QUEST_LV_0100_en.tsv

### PR DESCRIPTION
**Pull request by xapher19**
I made some more grammatical corrections, to better the flow of the sentences.

### CODE REVIEW

**Comment by vegax87** [comment]
In QUEST_LV_0100_20150317_000013     you deleted a {nl} tag after "I warn you!" , it's a tag written by devs to define a new line, you shouldn't remove these tags

**Comment by xapher19** [comment]
I changed it as per the [wiki](https://github.com/Treeofsavior/EnglishTranslation/wiki). There it notes that the new line tags can be moved around as new lines in Korean may not be needed in English. If the devs wish it to remain, we can replace it.

**Comment by Sunaries** [comment]
'Black' in 'Soldier Black' is wrong. Vlock or Bloc is a better name for this soldier.

**Comment by xapher19** [comment]
But 블락 doesn't sound anything like Vlock or Bloc. ㅏ doesn't make an "o" sound it's pronounced like the "a" in "apple", also ㅂ is pronounced as a merge between a b and a p sound as in "ball" or "Paul". That's why I translated it as Black.

**Comment by Sunaries** [comment]
Black would be 블랙. I'd go with Blak then.

**Comment by xapher19** [comment]
That's a fair point and a good compromise. It's been edited.

**Comment by imcgames** [comment]
:+1:

**Pull request merged**
