### PR TITLE
Update ITEM.tsv

### PR DESCRIPTION
**Pull request by vegax87**
Added and corrected a lot of potions, stamina pills and EXP Cards

### CODE REVIEW

**Comment by Sunaries** [comment]
My personal opinion is that I like "Lv" more than "LV". It's easier and distinguish on the eye.

**Comment by vegax87** [comment]
I understand, but IMCGames used uppercase for item levels during CBT2, so I stick with it

**Comment by imcgames** [comment]
if Lv is better, we could change to Lv actually :wink:

**Comment by Sunaries** [comment]
@imcgames :thumbsup:

**Pull request merged**
