### PR TITLE
OBT Standards check

### PR DESCRIPTION
**Pull request by Sunaries**
Standards check just before OBT begins. Fixing inconsistencies and mistranslations.
The descriptions all attributes that are currently flagged in the data as the main attributes are also improved. Now let's hope this won't be changed since there are some duplicate lines but with an outdated effect.

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by imcgames** [comment]
:+1:

**Pull request merged**
