### PR TITLE
Minor Update

### PR DESCRIPTION
**Pull request by Sunaries**
- Fixed incorrect equipment/item names.
- Fixed inconsistencies.
- Fixes erroneous text.

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by imcgames** [comment]
:+1:

**Pull request merged**
