### PR TITLE
Update QUEST.tsv [Lines 1-1756]

### PR DESCRIPTION
**Pull request by ghost**
General grammar corrections, consistency fixes for spelling and capitalization and a few rewritten dialogue to remove redundancy and to create a more natural conversation.

### CODE REVIEW

**Comment by vtange** [comment]
Hi, thanks for all the work.

The ellipses (...) should be changed back to the original special character form. Me and IMCgames have already gone over this and believe it's okay to leave them the way they are. In fact, my current pull request will change all ...'s in QUEST into the special character form.

**Comment by ghost** [comment]
First 650 lines worked over. Will proofread those and 'x's and do the next 650 lines when I find the time.

**Comment by Senhart** [comment]
Closing this to update with the new main files.

**Comment by imcgames** [comment]
Seems like something's wrong and  we can't check the changes well with more than 1k edits. 
Could you break them down to smaller pull requests with the latest files?

**Comment by ghost** [comment]
Alright.

**Pull request closed without merging**
