### PR TITLE
Transfer proper nouns from wiki to ITEM_en.tsv

### PR DESCRIPTION
**Pull request by dlam**
These changes were made with these typos brought up in issue https://github.com/Treeofsavior/EnglishTranslation/issues/228 presuming they would be fixed.

### CODE REVIEW

**Comment by vegax87** [comment]
ITEM_20150317_001494:  Cryomancer Costume was correct, maybe you haven't updated your fork to the latest updates

**Comment by imcgames** [comment]
Updated without uncorrected lines
:+1:

**Comment by dlam** [comment]
~~Uhh.. I'm not sure that this was merged correctly. Do you want to revert and I can make a new PR?~~

~~i.e., master now has the "chyomancer" mistake...~~

~~Sorry I wasn't able to fix my PR in time. I just saw this haha, I'm not exactly working on this 24/7.~~

**Comment by dlam** [comment]
Nevermind, I see that you [fixed it separately](https://github.com/Treeofsavior/EnglishTranslation/commit/edc7694b40d0dd126bc9acd6a8e82188dc2cc4e6)!

**Pull request merged**
