### PR TITLE
Minor update

### PR DESCRIPTION
**Pull request by Sunaries**
Minor update - Standards check.

@imcgames 

I have a question. In ITEM, I often see the term "Great Plant Cataclysm". (식물재앙)
Is this an event different from Medzio Diena (Day of the Divine Tree)? Or was this the first name of the same event?

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by imcgames** [comment]
@Sunaries Yes, It is a same day, but has a different meaning, like between "Atomic Bomb" and "the Second World War". :+1:

**Pull request merged**
