### PR TITLE
ETC.tsv [7] Poisonous Kepa

### PR DESCRIPTION
**Pull request by grillo-delmal**
https://forum.treeofsavior.com/t/poisoned-poisonous-or-frenzied/39355/

I opened that thread to discuss the context of that line, most of the people agreed that "Poisonous Kepa" was the option that made most sense. 
We might be missing something since we are translating out of context, if there is any problem with this PR, please join the discussion.

### CODE REVIEW

**Comment by imcgames** [comment]
Well, the kepa is the also the one poisoned/addicted and that's why it had that name :smile:

**Comment by ttgmichael** [comment]
So is a Poisoned Kepa a seperate variant of Kepa or just a Kepa that is poisoned?

If it's a seperate variant, then the change makes some sense. would Toxic Kepa be just as good? Poisonous is a pretty long word.

**Comment by grillo-delmal** [comment]
Ended up reverting it to what it was translated before :) marked it with $ and erased the extra dot that was not in the Korean version.

**Comment by Staryx** [comment]
ttgmichael, toxic kepa would be the same as poisonous kepa but just more poisonous

**Comment by grillo-delmal** [comment]
In the end, IMC responded that the Kepa was sick, not poisonous, so i'll leave it as Poisoned :)

**Comment by Staryx** [comment]
okay my bad :+1:

**Pull request merged**
