### PR TITLE
wrong memo x

### PR DESCRIPTION
**Pull request by mamoruk**
:dizzy_face:

### CODE REVIEW

**Comment by Sunaries** [comment]
Why are you removing all these memo x's? @imcgames added these since they are unused and do not appear in the game.

**Comment by ttgmichael** [comment]
Yep, there's no need to remove the {memo X}'s they actually help us distinguish lines that are used from those that are unused. Makes translating ToS more efficient :)

**Comment by mamoruk** [comment]
please check the ETC_kor.tsv file ....

**Comment by ttgmichael** [comment]
@mamoruk IMC hasn't been adding memo X regularly on lines for the Korean file. I assure you that the lines that are memo X'd in the English files are properly memo X'd.

**Comment by mamoruk** [comment]
= =i found ETC_20150317_008379  already inused but it sign memo X

**Comment by ttgmichael** [comment]
Screenshot? 

Most lines though should be unused. It's best not to remove these tags as they are put there by IMC.

You can report this to @imcgames for them to update what needs to be memo'x :+1:

**Comment by ttgmichael** [comment]
huh, interesting. 

@imcgames I'll let you figure this out ^^

**Comment by mamoruk** [comment]
:dizzy_face: 
All other texts's 'memo X' I submited only exist in 'ETC.tsv'. However, 'ETC_20150317_008379' are correct in 'ETC_kro.tsv', so I'm not sure those texts been unused or not.

**Pull request closed without merging**
