### PR TITLE
Real Time Translation Item.tsv and Quest.tsv and Quest_LV_100.tsv

### PR DESCRIPTION
**Pull request by ttgmichael**
Just edits to some of the NPC's  dialogue in Klaipeda.

Also, the items you recieve as awards for completing quests in Miners' Village are currently "Minor" items, but I have a feeling it should really be "Miner" equipment. Reinforcement stone, not material (based on visual context) ^^ 

And for the warp scroll descriptions, you can teleport to any >activated < statues, not any statue in the world xD.

### CODE REVIEW

**Comment by Ryuknight** [comment]
kay +1

**Comment by ttgmichael** [comment]
I've added the lines from Quest_Lv_100.tsv

Again, the lines are more or less from every NPC dialogue up to the Crystal Mines.

**Comment by laurencee** [comment]
This commit has 3k changes 0139318e83af36401d079377103be7991db3c4c8
Should probably try to keep them smaller for individual pull requests people can review them easier

Looks pretty good to me though

**Comment by ttgmichael** [comment]
That commit was accidentally made from an outdated branch (which was because the official rep had just pushed in a lot of changes into ETC/ the markings were removed). Sorry about that. ^^;

**Comment by laurencee** [comment]
If you're using git yourself, you can perform rebases rather than merges to avoid having merges in the pull request.

It just makes the pull requests easier to read. :)

**Comment by imcgames** [comment]
The Pull Request is closed for issues regarding copyrights as stated in our main page. 
We will be updating you with details in the near future regarding this matter so please hold your Pull Requests until things the issue is resolved. 
We apologize for the inconvenience caused.

**Pull request closed without merging**
