### PR TITLE
Update ETC_en.tsv

### PR DESCRIPTION
**Pull request by healthytofu**

### CODE REVIEW

**Comment by Sunaries** [comment]
???

You added what has already been there. Korean shouldn't be present in the file where it should be English.

**Comment by vegax87** [comment]
healthytofu, you need to update your files first, these files are very old now...

**Comment by ensata** [comment]
It's not just the files. Everything is old. This is a pull request from March. Was it reopened on accident?

**Comment by imcgames** [comment]
We will close this pull request as the files seem to be from the old version. 
You may resend us the edits using the latest files.  :wink:

**Pull request closed without merging**
