### PR TITLE
Update QUEST_LV_0200.tsv

### PR DESCRIPTION
**Pull request by Tinybutmighty**
Add translation: Line 7062 & 7063

### CODE REVIEW

**Comment by Requinn** [comment]
I have already made a PR with this translation, just a heads up.

**Comment by Tinybutmighty** [comment]
Oh yea. Just saw. Sorry, new here. Can I somehow remove this PR?

**Comment by ttgmichael** [comment]
You can close it by pushing the button next to the comment button ^^

**Comment by Tinybutmighty** [comment]
Okay. Thank you.

**Pull request closed without merging**
