### PR TITLE
Steam Test Server - Update 10

### PR DESCRIPTION
**Pull request by Sunaries**
Proofread https://github.com/Treeofsavior/EnglishTranslation/commit/781e3be7b62ddca90f85c876d2c089c7243cf8f8 and https://github.com/Treeofsavior/EnglishTranslation/commit/249271aff9efacfd9d2726792a1c03a1be434e67 + standards check.

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by imcgames** [comment]
Thanks :+1:

**Pull request merged**
