### PR TITLE
Location name changes to fit Lithuanian grammar.

### PR DESCRIPTION
**Pull request by ttgmichael**
Taking advice from @Xenobius2501 at
https://github.com/Treeofsavior/EnglishTranslation/issues/581

Changes to the Lithuanian location names in ETC.tsv

I'm guessing: (let me know what should it be ^^)
Tiltas Valley has more than 1 bridge. -> Tiltu
Ramstis Ridge being called Pillar Valley (singular)  -> Ramscio
Dvasia Peak as Soul's Peak (singular) -> Dvasios
Poslinkis Forest as Shifted Forest (past-participle) -> Paslinkes
Septyni Glen as 7th Glen -> Septyntas 
Vieta gorge to Vietos for grammar's sake.
Veja to Vejos too
Kvailas to Kvailio

### CODE REVIEW

**Comment by Xenobius2501** [comment]
@ttgmichael 

Looks legit so far.

I'll try to lay the groundwork for further name fixes later today after I go through my usual workload - probably checking the remaining lines on location list comes first. Also, being new to GitHub in general - where would it be better to post suggestions - here, in the form of comments or back in #581 ?

**Comment by ttgmichael** [comment]
Great!

If you want to post a suggestion for something related to the changes I've made here, you comment here. If you want to post a suggestion about something new, you should post back in #581 so it's more organized. ;)

**Comment by ensata** [comment]
Since these are keywords that will appear more than once, it's good practice to simultaneously add them to a reference file, so that you won't lose track of it so easily. This pull request will close and vanish eventually.

**Comment by imcgames** [comment]
Since these are actually spread out in other files, we will try to change them together with the other files later on. 
So we'll close this merge for now.

**Pull request closed without merging**
