### PR TITLE
Grammatical and punctuation revisions between lines 675-1050

### PR DESCRIPTION
**Pull request by tdn015**

### CODE REVIEW

**Comment by Darumy** [comment]
Hello! I proofread overlapping lines (1000-1050) and you caught some things I did not. I'll be copying your proofreads onto my PR so that if they merge mine second, your work won't be reversed. It's my bad, I should've included the edited lines in my title. Please do tell me if you are uncomfortable with this.

**Comment by ttgmichael** [comment]
@Darumy 

It doesn't seem like there are any overlapping lines, just overlapping regions. (you and tdn015 didn't work on the exact same lines).

Should be fine, unless git really screws up xD.

**Comment by Sunaries** [comment]
Good to merge. :+1:

**Comment by Sunaries** [comment]
@tdn015 Your pull request has merge conflicts. You will need to resolve this before it can be merged.

**Comment by tdn015** [comment]
Going to close this out since it looks like Darumy went ahead and copied my changes over to his. Thanks team!

**Comment by Sunaries** [comment]
@tdn015 He didn't take all the lines you proposed. Basically you closed the pull request while you had some good changes. If you don't mind, I'll add them to my pull request.

**Pull request closed without merging**
