### PR TITLE
Steam Test Server - Update 14

### PR DESCRIPTION
**Pull request by Sunaries**
Proofread: https://github.com/Treeofsavior/EnglishTranslation/commit/56f4754222c53c2a21d4960ebc004e27def34cab + https://github.com/Treeofsavior/EnglishTranslation/commit/e840aa9c7834ae9efd4b802b76c3031cbbcc5470 + https://github.com/Treeofsavior/EnglishTranslation/commit/da9bcb971cd6158d67bcfbec7833c0dd376d4d05

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by imcgames** [comment]
:+1:

**Pull request merged**
