### PR TITLE
Update ETC.tsv

### PR DESCRIPTION
**Pull request by Tkwanshuffle**
Whoops, thanks Rez.

Checked mostly for grammatical, capitalization's, and general corrections for better wording from line 12736 to the end of the file. Avoided any specific corrections to any lines where there were parts of the game I was unsure about its meaning relative to the content.

Will make sure future pulls are kept below the 100 line limit.

Anything else that I need to change or add here Rez?

### CODE REVIEW

**Comment by Rezken** [comment]
Please read the guidelines before doing Pull Requests.
https://github.com/Treeofsavior/EnglishTranslation/wiki/Guidelines

**Comment by Tkwanshuffle** [comment]
Corrected the original post. Also, read some other pulls to get an idea of how others are suggesting fixes. Will be sure to be more thorough and pre-check pulls in the future. With that said, it doesn't look like there's any conflicting pulls in here. Sunnaries  was the only other one to do the ETC.tsv file after its update 3 days ago, and he stopped just before where I began this one around line 12000. 

With that said, I do have one question: I kept wondering what the {nl} was for in multiple areas. Can you explain the purpose of that?

**Comment by cordogames** [comment]
@Tkwanshuffle  {nl} is a line break, stands for "new line".

**Comment by Tkwanshuffle** [comment]
Got it. Thanks.

**Comment by imcgames** [comment]
The Pull Request is closed for issues regarding copyrights as stated in our main page. 
We will be updating you with details in the near future regarding this matter so please hold your Pull Requests until things the issue is resolved. 
We apologize for the inconvenience caused.

**Pull request closed without merging**
