### PR TITLE
QUEST_JOBSTEP lines [400-500]

### PR DESCRIPTION
**Pull request by terrapin47**
Grammatical changes, typos.
Changes instances where bosses are referred to as plural.

### CODE REVIEW

**Comment by terrapin47** [comment]
Do not pull until https://github.com/Treeofsavior/EnglishTranslation/pull/879 has been accepted/resolved please.

**Comment by terrapin47** [comment]
Resolved merge conflicts.

**Comment by terrapin47** [comment]
Resolved conflicts from recent PR.

**Comment by imcgames** [comment]
Thank you :+1:

**Pull request merged**
