### PR TITLE
Steam Test Server - Update 8

### PR DESCRIPTION
**Pull request by Sunaries**
https://github.com/Treeofsavior/EnglishTranslation/commit/be26ac4e8ba38a0891ececf24fb16e0fb6d1821f proofread + other fixes.

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by imcgames** [comment]
:+1:

**Pull request merged**
