### PR TITLE
Update QUEST_LV_0300.tsv

### PR DESCRIPTION
**Pull request by HelpfulKoreanGirl**
Add translation lines 100-142

Spaces -> Tabs

### CODE REVIEW

**Comment by HelpfulKoreanGirl** [comment]
@imcgames  QUEST_LV_0300_kor.txt also needs to be changed to QUEST_LV_0300_kor.tsv

**Comment by imcgames** [comment]
@HelpfulKoreanGirl  Good point :+1:

**Comment by Sunaries** [comment]
Good to merge. Great work. :+1:

**Comment by imcgames** [comment]
:+1:

**Pull request merged**
