### PR TITLE
Update SKILL.tsv [Lines 17-1500]

### PR DESCRIPTION
**Pull request by cordogames**
Grammar, punctuation, and sentence structure fixes. [Lines 17-1500] shouldn't conflict with any existing pulls for SKILL.tsv

### CODE REVIEW

**Comment by Rezken** [comment]
Good job on this one!
Remember to keep your editing ranges in 50-100 lines though.

**Comment by cordogames** [comment]
Hey, when they mention 50-100 lines I was under the impression that the changes should be done to 50-100 lines not a 50-100 line range. Will do from now on, thanks for the tip.

**Comment by cordogames** [comment]
Kept this pull open as it didn't have any conflicts, I'll look over my other pull requests and fix conflicts for CBT version. :)

**Comment by imcgames** [comment]
The Pull Request is closed for issues regarding copyrights as stated in our main page. 
We will be updating you with details in the near future regarding this matter so please hold your Pull Requests until things the issue is resolved. 
We apologize for the inconvenience caused.

**Pull request closed without merging**
