### PR TITLE
Update ETC.tsv

### PR DESCRIPTION
**Pull request by TendrilTender**
Fixed some sentences and typos. Changed all instances of Revelator to Oracle.

### CODE REVIEW

**Comment by Chaosbelow** [comment]
Revelator is a term for the player character not the name of the class in this instance. This was reffered to in issue #50 and #120 but we need more context. For now 계시자 translates directly to Revelator so leave it at that.

**Comment by TendrilTender** [comment]
Noted eith the Oracle thing, changed it back in the places it doesn't refer to the class. I had failed to realize the context on the Line about harugals, changed it to your version. Where is the spacing wrong though? Can't seem to find it.

Thanks for the feedback!

**Comment by Chaosbelow** [comment]
Great work, keep it up. Line 11309: 
+ETC_20150428_011309_The mysterious instead of 
+ETC_20150428_011309___ The mysterious

The underscore is represented as space. 
Notice the indentation? Match it up with the rest of the lines before and after it. 
Sorry if its a bad explanation.

**Comment by TendrilTender** [comment]
Hmm, I can see that it's wrong when I look at the changed lines, but when i look at the actual file it looks aligned correctly. Not sure what to do about this.

**Comment by TendrilTender** [comment]
There, fixed it. Not sure what the cause was, so I just copied over the old line and used that instead.

**Comment by Chaosbelow** [comment]
:+1: Great work!

**Comment by imcgames** [comment]
Thank you :smile:

**Pull request merged**
