### PR TITLE
Proofreading IMC's lines - Part 2

### PR DESCRIPTION
**Pull request by Sunaries**
Fixes to: inconsistencies, incorrect map names gibberish, typos etc.

@imcgames I have a few questions. 

Q1 In the translations your team submitted, I sometimes see weird characters like question marks in it. An example would be: 

> +ITEM_20151224_009714 ��ī�� Flower

(Note: 마카지 = ? - I believe I translated it as Markazi)

Q2 I found typos in ETC_kor. I don't know which one is true. 카호르 or 카호스 (마법진)

@JayShee Can you please check IMC's translated lines? I've done a bit of work on them, but due to lack of time I cannot finish it today. Here's the link: https://github.com/Treeofsavior/EnglishTranslation/commit/103a5764e325a8623c770ac6fa328edc2a009932 - There's a lot of faulty English lines that really need attention and need to be reworked. These cannot really be in the game... You can check the work I've done on them through the commits and continue from where I left off.

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

**Comment by ttgmichael** [comment]
I believe you deleted a lot of the tabs you made on another PR?

**Comment by Sunaries** [comment]
The developer fixed that in a new version. Unfortunately, it did remove the current tabs to none to the lines. I wish the developer would've fixed the program for it only to recognize it in the future. Oh well...

**Comment by imcgames** [comment]
@Sunaries 
Q1. Question marks are some name needed to be named like "마카지", we will fix it soon.
Q2. I'm not sure but it seems "카호르" is correct word in game side.

**Comment by imcgames** [comment]
Thank you :+1:

**Pull request merged**
