### PR TITLE
Translated missing lines from 13001 to 13105, etc

### PR DESCRIPTION
**Pull request by Motevo**
Fixed "command" translations to "mission" since people think slash commands and whatnot when you say command. Added the missing lines from 13001 to 13105.

### CODE REVIEW

**Comment by ttgmichael** [comment]
Ack, the N/A lines didn't need translating xD (sorry, my pull request was misleading >.<)

Oh well. Thanks for the effort haha. :P

**Comment by Motevo** [comment]
So what does need translating?

**Comment by wlghksdl2** [comment]
There are item descriptions and flavor texts waiting to be translated in item.tsv.

**Comment by imcgames** [comment]
Yup, actually, N/A don't really need to be translated :sweat_smile: 
But thank you for your efforts :+1:

**Pull request merged**
