### PR TITLE
2nd iCBT: Minor fixes

### PR DESCRIPTION
**Pull request by Sunaries**
Fixed minor typos, errors and inconsistencies.

@imcgames I have questions about the 관음장 skill of Monk class.

 "대상을 손날로 강하게 내려쳐 방어구를 파괴합니다." - It says that it breaks/destroys the armor of a target. But there is an attribute 관음장: 방어구파괴 that says "스킬 [관음장]에 피격 된 적은 40% 확률로 7초동안 [아머브레이크] 상태에 빠집니다." - This attribute afflicts [Armor Break] state on enemies hit by 관음장 for 7 seconds at 40% chance.

Some players have told me and tested that 관음장 does not break/destroy armor of target without 관음장: 방어구파괴, even though the description of 관음장 says it does. What does 관음장 do without attribute? Is the description in Korean not up-to-date? Does it only deal damage to an enemy without the attribute?

Thanks to:
- https://forum.treeofsavior.com/t/archer-feedback-including-some-class-changes/119782
- https://forum.treeofsavior.com/t/i-can-not-craft-karacha-dagger/120699
- https://forum.treeofsavior.com/t/the-market-ui-needs-serious-work-list-of-problems/120580
- https://forum.treeofsavior.com/t/programming-bug-part-for-text-and-stuff/117456/3
- https://forum.treeofsavior.com/t/early-monk-feedback/119498/36

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge. :+1:

**Comment by Sunaries** [comment]
Good to merge. :+1:

**Comment by imcgames** [comment]
I will check your point with our Dev team. I think it seems not up-to-date in Korean scripts or just bug. 
Thank you @Sunaries  :+1:

**Comment by Sunaries** [comment]
Thank you @imcgames  

If you get an answer back, you can reach me on Discord or through my e-mail as always, so I can update it appropriately. :smiley:

**Pull request merged**
