### PR TITLE
Update ETC.TSV + SKILL.tsv

### PR DESCRIPTION
**Pull request by Just2good**
Fixed Linker Skill TL Error - Line 5718.

Edited lines for proper English sentence structure.

### CODE REVIEW

**Comment by grillo-delmal** [comment]
Remember to put the $ marks before the translated string (as defined in #900)
Example: 

```
ETC_20150317_005718 $Spiritual Chain
```

**Comment by Just2good** [comment]
Ah good to know, thanks!

**Comment by Just2good** [comment]
Weird, editing a few lines inside SKILL.tsv made some automatic changes to Lines 3151, 3805, 4158, and 4200 after commiting.

**Comment by imcgames** [comment]
Thank you :+1:

**Pull request merged**
