### PR TITLE
Update QUEST.tsv

### PR DESCRIPTION
**Pull request by RDawn**
It's my first time making a contribution here and I'm still not quite familiar with all of this. I do apologize for committing right away before making a pull request. Thank you.

### CODE REVIEW

**Comment by ensata** [comment]
You removed some of the flavor and altered the meaning of some sentences. I already retranslated the first 250 lines, weeks ago.

**Comment by RDawn** [comment]
Not really. I tried to make some of the sentences cohesive as possible since they seem too redundant. Also, they are still within the context from which they were edited.

**Comment by ghost** [comment]
The x's in front of the line names (xQUEST_20150317_000002) indicate that they were finished and needed no further editing.

Read about them here: https://github.com/Treeofsavior/EnglishTranslation/issues/540

Besides that, yeah they're okay as they are. (The original translations I mean.)

**Comment by Sourpusss** [comment]
@imcgames please do not publish this pull - it removed x's and made arbitrary changes (will waste further time in the future).

**Comment by ensata** [comment]
You've altered the meaning of many sentences by swapping out specific words, including Keywords (ie. Demons -> monsters), and you replaced almost every single ellipse and em dash with basic periods and commas. And damnit again, you misinterpreted the word "bony-looking". I thought I made that clear enough this time around.

Also, upon closer examination, I suspect that you are working off the files downloaded from the CBT, which was one day older than the files on GitHub, as of the day it was made available on Steam on Friday.

**Pull request closed without merging**
