### PR TITLE
Nicus

### PR DESCRIPTION
**Pull request by nicus101**

### CODE REVIEW

**Comment by Sunaries** [comment]
Hello @nicus101 @tokyoraider @Sajx. We only accept English translations and not of other languages on this repo. 
Therefore, this PR cannot be merged and should be closed.

**Comment by vtange** [comment]
This is in Polish, not English. Nice work, but you might want to double check your Git remotes if you meant to push to a different master. ;)

**Comment by tokyoraider** [comment]
Yes, this was apparently PR'd by our friend Nicus by mistake. Sorry for
that.

2015-11-09 20:59 GMT+01:00 Victor Tang notifications@github.com:

**Comment by imcgames** [comment]
Closed. We only accept English translations.

**Pull request closed without merging**
