### PR TITLE
Update QUEST.tsv

### PR DESCRIPTION
**Pull request by Sunaries**
Changed a few instances to put the emphasis on Goddess Statue.

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

**Comment by ttgmichael** [comment]
Yep, but it does seem it has conflicts now? o-o

**Comment by Sunaries** [comment]
> Yep, but it does seem it has conflicts now? o-o

Oh, weird. It was OK the last time I checked.

**Comment by laurencee** [comment]
_Same comment I put on your other PR_

Probably because IMC has merged a bunch of stuff, just rebase off the latest from IMC and fix any conflicts your side. Then this PR will be good to go!
1. Fetch treeofsavior:master
2. Rebase your patch branch onto treeofsavior:master locally
3. Fix conflicts and force push your local branch to your github forked branch

The PR will reflect those changes automatically.

**Comment by Sunaries** [comment]
> Same comment as your other PR:
> Probably because IMC has merged a bunch of stuff, just rebase off the latest from IMC and fix any conflicts your side. Then this PR will be good to go!

I see. Well, IMC merged a PR of @vtange - He edited the following line:
QUEST_20150317_000603   _$It's impossible to see the gigantic statue of Gemina all at once. {nl}Even after its lower half was buried underground after the huge earthquake._

However, this is wrong and should be, like: _It's impossible to see the gigantic Goddess Zemyna Statue all at once. {nl}Even after its lower half was buried underground after the huge earthquake._
which is addressed in my PR.

@imcgames Good to merge, I guess.  :)

**Comment by laurencee** [comment]
> I see. Well, @imcgames merged a PR of @vtange - He edited the following line:
> QUEST_20150317_000603 $It's impossible to see the gigantic statue of Gemina all at once. {nl}Even after its lower half was buried underground after the huge earthquake.
> 
> However, this is wrong and should be, like: It's impossible to see the gigantic Goddess Zemyna Statue all at once. {nl}Even after its lower half was buried underground after the huge earthquake.
> which is addressed in my PR.

As part of your "fix conflicts locally and push" step you can fix up this translation as well. Good pick-up on that error, unfortunate it wasn't in his PR.

**Pull request closed without merging**
