### PR TITLE
Update ITEM.tsv

### PR DESCRIPTION
**Pull request by RenzuMame**
Changed Sabre to Saber (US English)

### CODE REVIEW

**Comment by Chaosbelow** [comment]
Sabre is still spelled as Sabre in English. Saber is not the name of the weapon.

**Comment by RenzuMame** [comment]
Is it not? I used this as reference: https://en.wikipedia.org/wiki/American_and_British_English_spelling_differences

**Comment by Chaosbelow** [comment]
Well you are right that it can be spelled both ways but the more common way is Sabre. There is also really no reason to change it.

**Comment by RenzuMame** [comment]
The Style Guide says to use US English, so yeah.

**Comment by imcgames** [comment]
Let's keep sabre for sabers for now :smile:

**Pull request closed without merging**
