### PR TITLE
realtime ETC updates

### PR DESCRIPTION
**Pull request by terrapin47**
Various quest related description changes.

Notable change:
-ETC_20150729_014002    Resistance to the effects
+ETC_20150729_014002    Resist

The text was too large and verbose.

### CODE REVIEW

**Comment by Sunaries** [comment]
I believe Hallowventer is Hallowventor. But other than that, it is good to merge.

**Comment by terrapin47** [comment]
Hmm it's consistently Hallowventer everywhere else.  If we change it, we should change all of them at once.

**Comment by terrapin47** [comment]
Resolved conflicts.

**Comment by imcgames** [comment]
Thank you :smile:

**Pull request merged**
