### PR TITLE
Proofreading IMC's newest lines. Preparation for Steam TS.

### PR DESCRIPTION
**Pull request by Sunaries**
@imcgames 

The cleanup looks good. It was needed to remove all the {memo x}'s. 
Since you removed all the $ marks, I can only assume that this will no longer be supported anymore?

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by imcgames** [comment]
Maybe yes, we won't be using the $ marks anymore. But if we need, I will add it again. :+1:

**Pull request merged**
