### PR TITLE
Update QUEST_LV_0100_en.tsv

### PR DESCRIPTION
**Pull request by bonospeak**
until 4100

### CODE REVIEW

**Comment by Sunaries** [comment]
I don't understand why you deleted a lot of good lines.

**Comment by vegax87** [comment]
@bonospeak  please explain why you deleted a lot of lines, if they're wrong we could just edit them

**Comment by MasterCyria** [comment]
There are some spelling mistakes/name inconsistency formats that will need to be corrected in lines 4078-4100 if this is merged

**Comment by bonospeak** [comment]
Actually, I didn't touch lines other than 4000-4100.
I guess the reason for other lines being deleted could be that my file was out of date at the point when I sent the pull request?

**Comment by imcgames** [comment]
Thank you :+1: 
Clearly Updated.

**Pull request merged**
