### PR TITLE
Add Translation QUEST_300 Lines 1-99

### PR DESCRIPTION
**Pull request by HelpfulKoreanGirl**
Resolved merge conflicts and incorporated overlapping lines translated by neon279 in PR#1339.

Also revised lines 1-11 translated by vtange.

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge. :+1: Thank you.

**Comment by HelpfulKoreanGirl** [comment]
This PR was ready to be merged... but then @imcgames merged PR#1339, which contains a bunch of lines I revised and incorporated into this PR, so I don't really know what to do with these lines. Did you prefer those translations over mine?

**Comment by ttgmichael** [comment]
Merge conflicted fixed; Good to merge @imcgames :+1:

**Comment by imcgames** [comment]
Thank you @ttgmichael and @HelpfulKoreanGirl  :+1:

**Pull request merged**
