### PR TITLE
Update QUEST.tsv

### PR DESCRIPTION
**Pull request by megaoka**
Translating again!

### CODE REVIEW

**Comment by ensata** [comment]
Um, are you translating or are you editing? I re-translated lines 1-150 last weekend, and I think you made a few lines inaccurate by adding words.

The unicode ellipsis was added by me. There's a technical reason for why I recommend using them, but it wasn't discussed properly last week.

**Comment by Sourpusss** [comment]
Don't change ellipsis, please.  Literally all ellipsis are ".. " within the database.  It's best to just leave them how they are, than start changing them and miss some.

**Comment by megaoka** [comment]
You can change all the elipsis back, but they're a large majority "..." not "…"

it's all over the place. Wouldn't it be better to change it to be uniform than just not change it at all?

@ensata, translating and editing. If you disagree, I do not mind changing them back. If there's a technical reason for using unicode ellipsis, it's a very easy change to fix all the types of ellipsis we have on the project.

**Comment by ensata** [comment]
Actually, the majority is currently "..", and no one seems to want to fix or standardise it, even though it's incorrect grammar. But we shouldn't discuss that here.

Anyway.
In line 37, the second sentence should be a singular 'companion', but I prefer the original.
In line 77, Henrica never says 'Welcome', but that's a bit frivolous. Whatever.

**Comment by megaoka** [comment]
Yeah, I meant ".." not "..." just coming back to the project after surgery so I'm a little out of the loop right now.

I've changed line 77 back. I'll find another section to work on if you are going through this one methodically. I don't mean to redo work that's already been done.

**Comment by Sourpusss** [comment]
It's fine, lol.  But yeah, for simplicity's sake and uniform in the incorrect, just leave them.  Technically, ellipsis shouldn't be used that way in the first place.  It's meant for omission, not pause.  But this is an online game, not a thesis.

**Comment by imcgames** [comment]
Thank you and welcome back  :grinning: 
I hope you're alright now :pill: :syringe:

**Pull request merged**
