### PR TITLE
Update ITEM_en.tsv

### PR DESCRIPTION
**Pull request by megaoka**
Minor changes.

Made a few fixes as per the discussion here: https://github.com/Treeofsavior/EnglishTranslation/issues/354

Unsure about lines 2285 and 2286. Is Violet a monster, named/boss monster, or NPC? "Violet Flower" sounds too much like "a flower that is violet"

(and corrected a typo I made)

### CODE REVIEW

**Comment by emailboxu** [comment]
Actually 2286 should be Violet's Crystal, I should have checked with the KR file when I translated that. There's no 'of' for Violet Flower but I'm guessing it's the same.

**Comment by emailboxu** [comment]
Unless it's a common mob. Either way might be safer to leave the possessive in there.

**Comment by megaoka** [comment]
I wasn't  sure, because I didn't see "Violet" in the mobs list, but it's also strange because it's already a noun.. I think the possessive is a safer change if you want to make it.

**Comment by imcgames** [comment]
Violet is just a monster :+1:

**Pull request merged**
