### PR TITLE
Minor fixes (Complete)

### PR DESCRIPTION
**Pull request by Sunaries**
Minor fixes using the test server.

Also, I've changed 'Medis Diena' to 'Medzio Diena' as the proper term in Lithuanian. Change was made possible after permission was given from IMC.

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge. Resolved merge conflicts. :+1:

**Comment by imcgames** [comment]
:+1:

**Pull request merged**
