### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by Sunaries**
- Standard check for 'royal forces/kingdom soldier', replaced with 'Royal Army'
- Premier Eminent has the role of chancellor.
- Renamed Karlusto to Karsto. The latter is the actual transliteration and 'Karsto' is Lithuanian/Latvian.
- Several suggestions incorporated made by user Kuro-pi: https://forum.treeofsavior.com/c/beta-test-bug-report/translation

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

Last update added spaces because I was trying out the "Translator Helper" tool which is a convenient tool to check whether a dialogue line is too long or not. But the tool is not stable yet. My apologies.

**Comment by Sunaries** [comment]
Good to merge.

Last update added spaces because I was trying out the "Translator Helper" tool which is a convenient tool to check whether a dialogue line is too long or not. But the tool is not stable yet. My apologies.

@imcgames Do you have status on my request from October? See >>> https://github.com/Treeofsavior/EnglishTranslation/pull/1246 - Because you have forwarded it to the developer team and I don't know what happened to it. Thank you. :smiley:

**Comment by Sunaries** [comment]
Good to merge.

Last update added spaces because I was trying out the "Translator Helper" tool which is a convenient tool to check whether a dialogue line is too long or not. But the tool is not stable yet. My apologies.

@imcgames Do you have status on my request from October? See >>> https://github.com/Treeofsavior/EnglishTranslation/pull/1246 - Because you have forwarded it to the developer team and I don't know what happened to it. Thank you. :smiley:

**Comment by imcgames** [comment]
@Sunaries Yes, Our dev team already knew these issues and it will be fixed before starting KOBT.

**Comment by imcgames** [comment]
:+1:

**Pull request merged**
