### PR TITLE
HelpfulKoreanGirl's Light of Salvation Edit

### PR DESCRIPTION
**Pull request by vtange**
Pulled from #1301 and fixed merge conflict. Also changed QUEST100 9585 to Light of Salvation.

### CODE REVIEW

**Comment by HelpfulKoreanGirl** [comment]
Thanks vtange! I couldn't figure out how to fix the merge conflict >.<

**Comment by HelpfulKoreanGirl** [comment]
Closed my PR!

**Comment by ttgmichael** [comment]
This ought to be good to merge. :+1:

**Comment by Sunaries** [comment]
:+1:

**Comment by imcgames** [comment]
:+1:

**Pull request merged**
