### PR TITLE
Steam Test Server - Update 12

### PR DESCRIPTION
**Pull request by Sunaries**
Proofread https://github.com/Treeofsavior/EnglishTranslation/commit/c9adacbb14738de2da55958b7e5a318a2efc226f + https://github.com/Treeofsavior/EnglishTranslation/commit/8d259cc8705b12131de80943f4073acc6e713ceb + portion of https://github.com/Treeofsavior/EnglishTranslation/commit/6dd44a9f652c46c721976523b3030ecb101c8f71

@imcgames I have 3 questions:

Q1. 신기전 is a skill. It was known as Singijeon and now is as Divine Arrow, however 'singijeon' is a literal romanization. What do you think of: "Divine Machine Arrow" - That is what I've changed it at. Of course, it is easy to replace this. 

Q2. About the new batch of KTOS data: What are the official spellings on the following names:

비르토브
롤로팬서
아티
비니
루마스
듀로
퓨테레
세이모스
아이라
펜사라
루마
자스
듀리스
에키
틸리
카스티

I'd rather hear it directly from you since these words can be interpreted differently.

Q3. I don't know what has been changed because of the massive changes from https://github.com/Treeofsavior/EnglishTranslation/commit/6dd44a9f652c46c721976523b3030ecb101c8f71 
Here is a link showing the changes, '_<_' = me, '_>_' is yours: http://pastebin.com/raw/gsszweFc
The link above shows the differences and it is clearly evident that a lot of lines have been reverted.

**Examples)**

QUEST_LV_0100_20151224_013437   Napalis said you saved them from a really close call.{nl}I'm glad they're back to safety, but I can't guarantee things like this won't happen again.
QUEST_LV_0100_20151224_013437   나팔리스 said you saved them from a really close call.{nl}I'm glad they're back to safety, but I can't guarantee things like this won't happen again.

QUEST_LV_0100_20151224_013782   Check for requests at the Mercenary Post.
QUEST_LV_0100_20151224_013782   Check for requests at the Commisioner's Office.

QUEST_LV_0100_20151224_013499   Corpse Poison [Wugushi Advancement]
QUEST_LV_0100_20151224_013499   Corpse Poison [Wuguxi Advancement]

QUEST_LV_0100_20151224_013158   Margiris is on the way to Carlyle's Mausoleum.{nl}With the spirit rock you should have no problems in joining our sect.{nl}
QUEST_LV_0100_20151224_013158   Marugiris is on the way to Carlyle's Burial Chamber.{nl}With the spirit rock you should have no problems in joining our religious body.{nl}

And that's just a portion I could see. It is very disappointing that this is still happening...
I've reverted a lot back to the good version in this pull request.
**Next time, post smaller updates. Github only allows up to 300 additions/deletions before it comes unviewable.**

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Good to merge.

**Comment by imcgames** [comment]
First of all, sorry about that happened again. 
I will revert Quest_Lv_100 to the good to version. After that, I will leave the comment about your questions. thanks.

**Comment by Sunaries** [comment]
@imcgames I have already reverted a big amount of lines in this pull request. Since it was too much, I couldn't keep track on every single change. I will be anticipating your answers about the questions.

**Comment by imcgames** [comment]
Q1. 신기전 : We want to use "Divine Machine Arrow. seems to be more accurate.
Q2. New names : 
비르토브 Virtov
롤로팬서 Lolopanther
아티 Artie
비니 Vienie
루마스 Lumas
듀로 Duro
퓨테레 Futere
세이모스 Seimos
아이라 Ira
펜사라 - Pensara
루마 - Ruma
자스 - Jaas
듀리스 - Duris
에키 - Eki
틸리 - Tilly
카스티 - Khasti

**Comment by imcgames** [comment]
Q3. I am so sorry about that. and We can revert to the good version compared to the last version. We will keep it in mind. Please wait a moment.

**Pull request merged**
