### PR TITLE
Update SKILL.tsv

### PR DESCRIPTION
**Pull request by emailboxu**
Posion -> Poison
1 time(s) -> 1 time
2+ time(s) -> 2+ times
Attack area -> AoE (Area of effect, common term that should be familiar)
Fan-shaped -> Conical
Head-butt -> Headbutt
Fuem -> Fume
X hand/X-hand -> X-handed
Removed instances of triple commas 

Translated as much of the Korean stuff as I could find. Point out more if they exist.

Stopping because I'm at 269. Limit of 300 per PR, right?

### CODE REVIEW

**Comment by ensata** [comment]
AoE should be written fully, since that's advanced jargon. New players won't understand what it means. You should never use acronyms. 'Fan-shaped' should be 'Conical'. It's de facto western RPG terminology. 'Fan-shaped' is a de facto eastern RPG term.

Also, the 300 rule was supposed to be a range limit, not a number limit... you're at a range of 5000. Ah, whatever. Just don't blame me if the merge gets complicated.

**Comment by Flevalt** [comment]
"Stopping because I'm at 269. Limit of 300 per PR, right?"

You're at +269 −269. Making it a total of 538.
Not sure how I feel about AoE instead of Area of Effect.
I think it should be fully written out so it is comprehensible for everyone. But people would figure it out in due time anyway if they didn't already know.

**Comment by emailboxu** [comment]
I don't think people will have problems with AoE. It's an extremely common abbreviation in many games. As for the range I just replaced all so I don't think it should mess with it too much.

**Comment by ensata** [comment]
You shouldn't assume that. Everyone was a beginner at some point, and info blurbs are supposed to give info to everyone.

"Fan-shaped Attack Area" was perfectly fine, too, at least for now. It's very "eastern", but you insisted that "Swordsman" made perfect sense, too. A reference file for translating the game's game mechanic terminology doesn't exist yet, either.

**Comment by ghost** [comment]
I agree that "fan-shaped" or  "cone-shaped" would've been an easier to understand term for younger players and less English savvy players. I've used the word 'Conical' maybe four times in my life. "Area of effect" should stay as well if it turns out it'll fit just fine in the UI. Making things easier for beginners should take priority over making things convenient for veterans.

And yes you kind of went over the range, no one (Or at least I wouldn't) can really touch lines 2 through 4264 now because of potential merge issues.

**Comment by imcgames** [comment]
Thank you :smile: 

(We'll try to have AoE back to Area of Effect later but I'm afraid it may be too long when for UI. 
Let's see during how it goes during Beta.)

**Comment by emailboxu** [comment]
The length was the exact reason I didn't put it in. If there's room for it then I don't mind switching the two later.

**Pull request merged**
