### PR TITLE
Talt "flavor" text

### PR DESCRIPTION
**Pull request by Sourpusss**
Added as a gaming joke for the notoriously annoying boss drop.  Feel free to ignore this request, but I've heard many players make this joke, so it'll probably be well received.

### CODE REVIEW

**Comment by vtange** [comment]
I don't get it, mind explaining?

**Comment by Sourpusss** [comment]
Getting the currently useless talt makes people "salty" or "bitter" towards receiving the token, in comparison to equipment.

**Comment by ttgmichael** [comment]
> Getting the currently useless talt makes people "salty" or "bitter" towards receiving the token, in comparison to equipment.

A strange gemstone sometimes found in monsters. Captivated by its mysterious color, many collectors seek this gem, while others wonder why they would choose to collect such a salty gemstone.

?

**Comment by Sourpusss** [comment]
I like that way, but I don't really think the wording of "salty gemstone" works all that well.  It's not that the stone itself is feeling salty, and no one should really be tasting gemstones anyway, so it kind of explicitly needs to be said that someone tasted it (but it's not expected for anyone to do so).

Once again, no pressure on you guys, IMC.  This is more of a player joke than actual lore ideas.

**Comment by ttgmichael** [comment]
Lol but the point of the meme is that out of all the flavors, you chose something salty xD. 
Just offering a suggestion :p

**Comment by stvkno** [comment]
I don't think this is necessary at all.. Translations should be as close to the original as possible with grammar/context fixes and not personal notes/interpretations of the original text

**Comment by Sourpusss** [comment]
You're right - it's not necessary.  It's just fun, and it gives the game some character.

Also, there's an arrow to the knee joke.  It's not like this is the first "extra" line added.

**Comment by Sunaries** [comment]
Except the "arrow to the knee" was literally there. :wink:

**Comment by Sourpusss** [comment]
Haha, well, kudos for IMC for the topical gaming humor.  Once again, this is just a frivolous suggestion based on current player feelings - just throwing ideas out there.

**Comment by vtange** [comment]
if IMC wants to add the joke, then good to merge

**Comment by imcgames** [comment]
I think it's good to merge. :+1:

**Pull request merged**
