### PR TITLE
2016.05.23 Difference between RECIPE from ETC vs. ITEM / Duplicated ETC ID

### PR DESCRIPTION
**Pull request by Sousou122**
### Update List:

**1. Update difference between RECIPE from ETC vs. ITEM**
Background:
Run a vlookup to compare all recipes from ETC file vs. items from ITEM file, make sure the translation are consistent with each other.

Result:
[ETC_ID] / [ITEM_ID]
ETC_20150317_008276 Recipe - Crook / ITEM_20150317_000219
Crook
**ETC_20150317_008277 Recipe - Puter Rod / ITEM_20150317_000221
Pewter Rod**
ETC_20150317_008278 Recipe - Owl Rod / ITEM_20150317_000223
Owl Rod

ETC_20150317_008294 Recipe - Staff / ITEM_20150317_000834
Staff
**ETC_20150317_008295 Recipe - Jus Staff / ITEM_20150317_000836
Ju Staff**
ETC_20150317_008296 Recipe - Ubuko Staff /
ITEM_20150317_000838 Ubuko Staff

ETC_20150317_008320 Recipe - Rokas Bow / ITEM_20150317_000318
Rokas Bow
**ETC_20150317_008321 Recipe - Goritos / ITEM_20150317_000320
Gorithos**
ETC_20150317_008322 Recipe - Gulail / ITEM_20150317_000322
Gulail

**ETC_20150714_012228 Recipe - Roxona Plate Gauntlet /
ITEM_20150714_005134 Roxona Plate Gauntlets**

**ETC_20160224_020484 Recipe - Luma Sword /
ITEM_20160224_009849 Ruma Sword**

**2. Delete duplicated ETC ID**
ETC_20151022_015924
ETC_20160224_020731
ETC_20150317_001460

### CODE REVIEW

**Comment by Sunaries** [comment]
For consistency, you would need to edit ITEM_20160224_009849 from Luma to Ruma.

**Comment by Sousou122** [comment]
Correct. But the original text for ITEM_20160224_009849 is **Ruma** Sword already.
So nothing need to change accordingly.

**Comment by Sunaries** [comment]
Woops, forgot about it. Your pull request looks good. 

Good to merge. :+1:

**Comment by Sousou122** [comment]
Just realized that, after pulling another minor commit: Duplicated ETC_ID ETC_20151022_015924.
It attached to the previous commit. Hope it doesn't make anything confusing. 
lol

**Comment by Sunaries** [comment]
Good catch! :+1:

**Comment by Sousou122** [comment]
**Complete the ETC duplicated ID check.**
Wondering if there is a PULL haven't been merged here. i can only attachment the new commit to this PULL, or can i raise a new PULL to have different description. the duplicated check result make the pull description doesn't accurate, and seems no way to change it.

**Comment by Sousou122** [comment]
Just found the way to update the PULL desc. 
Problem solved.

**Pull request merged**
