### PR TITLE
Proofreading, fixing Lithuanian names, NPC titles and other minor fixes

### PR DESCRIPTION
**Pull request by Sunaries**
EDIT: @imcgames Please check your e-mail. It is important regarding the English Translation!

Noticeable changes:
- **Renamed Bokor skill 'Samdiveve' to 'Samediveve' - Reason: https://en.wikipedia.org/wiki/Baron_Samedi**
- Corrected NPC names and titles. (e.g. Shetrigailla -> Svitrigaila)
- Gitis -> Gytis (Latvian name) - Please update Wiki in Map: Gitis Settlement Area -> Gytis Settlement Area
- Fixed erroneous sentences and names in quest dialogue and item descriptions.

**Bug**: Using Barbarian's Giant Swing skill on quest objects can make it go off-map, which means that you would need to re-do the quest since there are only a number of objects. 

@imcgames I had a few questions for you in my last pull request, but these were unfortunately not answered. They are important.

> Important questions for @imcgames to add these changes before 2nd iCBT:
> 
> **1.** What is the exact term for 누아엘레? Wiki says 'Nuahella', yet in the newly translated lines by you it says 'Nuaele', there are also instances of 'Nuaelle' in the files. I need to know the final name for consistency. Please update the wiki as well for this one.
> 
> **2.** 구원자 means Savior. However, in a few new lines you've translated it as 'Revelator'. Are they both the same? It's confusing. 
> Was '구원자' used in the early concept, but then switched to '계시자'?
> 
> **3.** 왕의 고 is referred as 'Plateau of Rex' in the Wiki. In the newly translated lines, it is referred as "King's Plateau", which is just the real translation. 
> I assume Rex was named after Rexipher? What should we do about this? For now, I'll change it to Plateau of Rex, but "King's Plateau" is the most suitable translation for it, though.
> 
> **4.** Can you please respond to this Issue https://github.com/Treeofsavior/EnglishTranslation/issues/1148 - This might be a bug?
> 
> **5.** Can you please respond to this Issue regarding a rename of an important item in the game?
> https://github.com/Treeofsavior/EnglishTranslation/issues/1192 
> 
> **6.** 비보라 is a Goddess. Is it: Vibora or Vivora (or Vivola? Virola?)
> 
> **7.** GitHub Logo
> 
> ↑ Data says he is Florijonas (플로리요나스), but the quests say he is Jonas (기록관 요나스) - Why?
> 
> **Last question.** Have you given thought about the 'Cabin Medium' font? There's many advantages to use this in the game, because it is also a bit smaller and it doesn't space things too wide which 
> is perfect for the game. Please try it out in iCBT2 and check player feedback. It's closed beta, so it's not final yet, right? :wink: You would do us, the contributors, a good favor.

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge as far as I know. :)

**Comment by Sunaries** [comment]
@imcgames Good to merge. I would appreciate if you could answer my questions, please. :smiley:

**Comment by terrapin47** [comment]
:+1: Nice job

**Comment by Sunaries** [comment]
@imcgames Good to merge. I would appreciate if you could answer my questions, please. :smiley:

**Comment by Sunaries** [comment]
@imcgames Good to merge. I would appreciate if you could answer my questions, please. :smiley:

**Comment by Sunaries** [comment]
@imcgames Good to merge. I would appreciate if you could answer my questions, please. :smiley:

**Comment by Sunaries** [comment]
@imcgames Good to merge. I would appreciate if you could answer my questions, please. :smiley:

**Comment by Sunaries** [comment]
@imcgames Good to merge. I would appreciate if you could answer my questions, please. :smiley:

**Comment by Sunaries** [comment]
@imcgames Good to merge. I would appreciate if you could answer my questions, please. :smiley:

**Comment by imcgames** [comment]
1. According to our dev team, "Nuaele" is correct.
2. 구원자 is Savior. I think the translated Revelator was a wrong work from our side.
3. "왕의 고원" is "King's Plateau. 
4. It seems a bug. I will check it with Dev team to fix.
5. We want to use Divine Sphere originally. Actually, it's not the horn.
6. His name is Florijonas. The reason mistranslated was that I think the head image of him has changed recently.
7. Current Font was decided by our Boss and he thought it was so good to display our game style.
   Like this reason, I'm not sure whether we can use "Cabin Medium font" officially or not. But I will try to check with him and dev team.

But don't worry, as you know user can change their font themselves. If they (user) want to use "Canin" or the other fonts, they can use it just replace it.

**Comment by imcgames** [comment]
Thank you :+1:

**Comment by imcgames** [comment]
ah, 비보라 is "Vibora"
Thank you :+1:

**Pull request merged**
