### PR TITLE
Update ITEM.tsv

### PR DESCRIPTION
**Pull request by Sunaries**
Minor fixes.

### CODE REVIEW

**Comment by terrapin47** [comment]
:+1: good to merge

**Comment by Sunaries** [comment]
Good to merge.

**Comment by Sunaries** [comment]
Currently figuring out to resolve the merge conflict.

**Comment by Sunaries** [comment]
@imcgames good to merge. Merging conflicts are fixed.

**Comment by imcgames** [comment]
Thank you :smile: 

(changed pond -> pawnd, pondell -> pawndel)

**Pull request merged**
