### PR TITLE
Update ETC.tsv (Through Realtime Translation)

### PR DESCRIPTION
**Pull request by Sunaries**

### CODE REVIEW

**Comment by Sunaries** [comment]
Good to merge.

**Comment by ttgmichael** [comment]
Perhaps add the $ for all the lines you have here and other PRs too? Then people will now what's been editted. ^^

**Comment by Sunaries** [comment]
> Perhaps add the $ for all the lines you have here and other PRs too? Then people will now what's been editted. ^^

Done. 

Now my PR says: "This branch has conflicts that must be resolved" - This is weird, this just happened to my other PR too. When I submitted the PR, it was OK for merge.

**Comment by laurencee** [comment]
Probably because IMC has merged a bunch of stuff, just rebase off the latest from IMC and fix any conflicts your side. Then this PR will be good to go!
1. Fetch treeofsavior:master
2. Rebase your patch branch onto treeofsavior:master locally
3. Fix conflicts and force push your local branch to your github forked branch

The PR will reflect those changes automatically.

**Comment by Sunaries** [comment]
Good to merge. :)

**Comment by laurencee** [comment]
:+1:

**Comment by imcgames** [comment]
Thank you :smile:

**Pull request merged**
