### PR TITLE
Update ITEM.tsv

### PR DESCRIPTION
**Pull request by Azioria**
Translations for lines 7030-7032, 7055-7058, 7062, 7064-7068, 7071-7082 (25 lines)

### CODE REVIEW

**Comment by imcgames** [comment]
"결계" is mean like "barrier" so it should be changed to like "barrier stone". What do you think?

**Comment by Azioria** [comment]
I think that sounds more accurate, as well. I've switched that as well as fixed lines 7026-7027 to be more consistent.

**Comment by Sunaries** [comment]
Looks good after the change. :+1: Good to merge.

**Comment by imcgames** [comment]
Thank you :+1:

**Comment by terrapin47** [comment]
Hi @Azioria, would you like to join us on Discord?  We're using it to discuss changes and help each other with the translation process.  You can join by clicking [here](https://discord.gg/0RoYSiES4f1LlZPF).

**Pull request merged**
