### PR TITLE
Update ITEM.tsv

### PR DESCRIPTION
**Pull request by seejy**
Few more adjustments to improve clarity.

### CODE REVIEW

**Comment by Sunaries** [comment]
Thank you for contributing. Can you please make your edits in a separate commit when it is in the same file. You can actually edit this pull request https://github.com/Treeofsavior/EnglishTranslation/pull/1219 of yours and update it, thus adding a commit. Or else this section will be cluttered with separate pull requests of the same file, when you can actually update everything in just one pull request. Thanks.

**Comment by seejy** [comment]
Sure thing. Sorry for the inconvenience caused!

**Comment by Sunaries** [comment]
Good to merge.

**Comment by imcgames** [comment]
:+1:

**Pull request merged**
